:sparkles: Add Synthetic Data Pages to ML
runtimerevolution/knowledge-base pull request #7
Opened 2023-05-26 15:28 UTC by vpais

2023-05-29 15:05 UTC, ghost commented on docs/python/machine_learning/synthethic_data/2_single_table.ipynb
To be more clear, I would suggest moving 
´´´
metadata.update_column(
    column_name='age',
    pii=True
)
´´´
right after: As you can see bellow, we then tried to say that Age is a PII column (Personally Identifiable Information) however that's not the case.
Also, it didn't working setting age as pii, so then what? It is a bit unclear as to the why it failed ( I am assuming it is because age is not unique for each row). Should there not be an example where you have success in setting a var as PII?

2023-05-29 15:08 UTC, vpais commented on docs/python/machine_learning/synthethic_data/2_single_table.ipynb
The explanation is bellow the error. It does not work because sdtype age is not a valid pii type. Since on that table the only possible PII at first glance was that column there is no more possible columns for that table to set as PII. Since that was the case, a second table is created in the multitable notebook which has PII columns and success cases (address, name, city)

2023-05-29 15:31 UTC, FilipaSdS commented on docs/python/machine_learning/synthethic_data/2_single_table.ipynb
How were the values for low_value and high_value chosen?
´´´
my_constraint = {
    'constraint_class': 'ScalarRange',
    'constraint_parameters': {
        'column_name': 'bmi',
        'low_value': 11.3,
        'high_value': 97.6,
        'strict_boundaries': False
    }
}

my_constraint2 = {
    'constraint_class': 'ScalarRange',
    'constraint_parameters': {
        'column_name': 'avg_glucose_level',
        'low_value': 55.12,
        'high_value': 271.74,
        'strict_boundaries': False
    }
}
´´´

2023-05-29 15:33 UTC, vpais commented on docs/python/machine_learning/synthethic_data/2_single_table.ipynb
Just changed the location to bellow the error and added a link to the multitable notebook with the following text:
Since age is not a PII column and neither are any of the other columns of this table, we'll test this PII setting on our [multitable](3_multi_table.ipynb) notebook once we have a people table with personal information.

2023-05-29 15:35 UTC, vpais commented on docs/python/machine_learning/synthethic_data/2_single_table.ipynb
Just added:
The values used for low and high values on the constraints are the same as the low and high values on the original data.

2023-05-29 15:41 UTC, FilipaSdS commented on docs/python/machine_learning/synthethic_data/3_multi_table.ipynb
Repeated twice: 
Change column name to type name and mark as PII;
Change column name to type name and mark as PII;

2023-05-29 15:42 UTC, FilipaSdS commented on docs/python/machine_learning/synthethic_data/3_multi_table.ipynb
maybe you wanted to say city?

2023-05-30 09:44 UTC, FilipaSdS approved these changes

2023-05-31 11:54 UTC, kenvontucky requested changes

2023-05-31 11:54 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +```
This should be replaced by a subsection called requirements, where it is mentioned that a the time this was written, de required Python version was >= 3.10 and < 3.11.

2023-05-31 11:54 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +In this section we'll explore the generation of synthetic data using SDV library. The SDV offers multiple machine learning models ranging from classical statistical methods (Copulas) to deep learning
Please add the url for SDV

2023-05-31 11:54 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +At first we need to load the data. If it stored in a csv format we can use the **[load_csvs](https://docs.sdv.dev/sdv/single-table-data/data-preparation/loading-data#load_csvs)** method. Otherwise si
sdv -> SDV

2023-06-06 11:21 UTC, kenvontucky requested changes

2023-06-06 11:21 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +Since SDV uses Pandas' dataframe under the hood, we can use it directly to load the data. However
`However` seems to be missing some sort of conclusion here, which might be the case that pandas only allows for one table to be loaded instead of the multiple allowed by `load_csvs`

2023-06-06 11:21 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +## Metrics
Lets add some context here, like why are these metrics presented and how were generated

2023-06-06 11:21 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +## Conclusion
Instead of a conclusion, perhaps code samples with links to the notebooks would make more sense here.

2023-06-06 11:21 UTC, kenvontucky commented on docs/python/machine_learning/synthethic_data/1_synthetic_data.md
> +# Introduction
Lets add a subsection for Personal Identifiable Information, just to inform what it is

2023-06-12 14:30 UTC, JdFSilva approved these changes

2023-06-12 14:30 UTC, JdFSilva commented on docs/python/machine_learning/synthethic_data/2_single_table.ipynb
nit: spelling mistake `as` should be `has`:
`The SDV library has a very powerful tool which allows you to evaluate the quality of the data`

2023-07-03 15:37 UTC, kenvontucky approved these changes

2023-07-03 15:38 UTC, merged